version: '2'
services:
  app:
    image: adoptopenjdk
    container_name: my-application
    ports:
      - "8080:8080"
    restart: always
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB: companydb
      MYSQL_ROOT_PASSWORD: root